# Generated by Django 4.2 on 2023-05-31 05:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuposttranslation',
            name='content_two',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='vacansiyapost',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='doc/'),
        ),
    ]
