# Generated by Django 4.2 on 2023-06-14 10:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_submenuposttranslation_content_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AddField(
            model_name='menutranslation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='content'),
        ),
    ]
