# Generated by Django 4.2 on 2023-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_post_posttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='posts'),
        ),
    ]
