# Generated by Django 4.2 on 2023-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submenupost',
            name='img',
            field=models.CharField(blank=True, null=True),
        ),
    ]
