# Generated by Django 4.2 on 2023-05-01 12:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmenuPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='posts')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SubmenuPost',
                'verbose_name_plural': 'SubmenuPosts',
                'ordering': ['-date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubmenuPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='admin_panel.submenupost')),
            ],
            options={
                'verbose_name': 'SubmenuPost Translation',
                'db_table': 'admin_panel_submenupost_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
