# Generated by Django 4.2 on 2023-05-02 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_submenupost_submenuposttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenupost',
            name='id_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.submenu'),
        ),
    ]
