# Generated by Django 4.2 on 2023-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_application_consultatsiya_forma'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ceo_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ceo_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenupost',
            name='ceo_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenupost',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vacansy',
            name='ceo_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacansy',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
