# Generated by Django 4.2 on 2023-05-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_vacansy_vacansytranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submenutranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submenutranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-date'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='submenupost',
            name='id_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.menu'),
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
        migrations.DeleteModel(
            name='SubMenuTranslation',
        ),
    ]
