# Generated by Django 4.2 on 2023-05-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_submenutranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacansiyaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('e_mail', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_vacanys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vacansy')),
            ],
        ),
    ]
